# -*- coding: utf-8 -*-
"""Focal_Loss

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tBm-zJq_wksvgNGbNA0sSTZSoPxUniT
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, inputs, targets):
        cross_entropy_loss = F.cross_entropy(inputs, targets, reduction='none', weight=self.alpha)
        pt = torch.exp(-cross_entropy_loss)
        focal_loss = (1 - pt) ** self.gamma * ce_loss
        return focal_loss.mean()