"""
El Mehdi Ziate


WHAT IS FASTER R-CNN:
R-CNN = Region-based Convolutional Neural Network.
The "Faster" means the region proposals are generated by the network
itself (not by a slow external algorithm like Selective Search).

The model works in TWO stages:

  Stage 1 Region Proposal Network (RPN):
    Slides over the feature map and asks at every location:
    "Is there an object here? If yes, give me a rough bounding box."
    Output: ~300 candidate boxes (called "proposals" or "anchors").

  Stage 2 RoI Head (Region of Interest):
    Takes each proposal, crops the feature map to that region,
    and classifies it into one of the 28 WaRP-D classes (or background).
    Also refines the bounding box coordinates.

  The BACKBONE (ResNet-50 + FPN) runs ONCE on the full image
  and produces a feature pyramid at multiple scales.
  Both RPN and RoI head share these features — this is what makes it fast.

  Input:  list of images  (variable size)
  Output: list of dicts   {"boxes": (N,4), "labels": (N,), "scores": (N,)}

WHY FASTER R-CNN FOR WARP-D:
WaRP-D has overlapping bottles on a conveyor belt.
Faster R-CNN's two-stage design handles overlap well because the RPN
first proposes boxes independently, then each box is classified separately.
A one-stage model like YOLO merges detection and classification into one
step which can struggle when two identical objects overlap heavily.

Faster R-CNN is the direct baseline from Yudin et al. (2024) who tested it
on WaRP-D. Our results are directly comparable to their Table.

ARCHITECTURE:
  ResNet-50-FPN backbone  →  256-dim feature pyramid (P2 to P6)
  RPN                     →  ~300 proposals per image
  RoI Align               →  crops features to 7×7 per proposal
  Two FC heads            →  classification + box regression

  Total parameters: ~41 million
  Pretrained on: COCO (80 classes) — we replace the final head for 28+1

FINE-TUNING STRATEGY:
  We use COCO pretrained weights. The backbone already understands
  "what objects look like". We only need to adapt the classification head
  to WaRP-D's 28 classes + 1 background = 29 total.

  Phase 1: freeze backbone, train RPN + heads only (5 epochs)
  Phase 2: unfreeze backbone, train everything with low backbone LR

Reference:
  Ren et al. (2015) Faster R-CNN: Towards Real-Time Object Detection
  with Region Proposal Networks. NeurIPS 2015.
  https://arxiv.org/abs/1506.01497
"""

import torch
import torch.nn as nn
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor


class FasterRCNNWaRP(nn.Module):
    """
    Faster R-CNN fine-tuned for WaRP-D 28-class object detection.

    Uses torchvision's pretrained Faster R-CNN (COCO weights) and
    replaces only the classification head for 28 WaRP classes.

    Parameters: 
    num_classes : int
        Number of WaRP-D classes + 1 background. Default 29.
    pretrained  : bool
        Load COCO pretrained weights. Always True unless debugging.
    score_thresh : float
        Minimum confidence score to keep a detection at inference.
    nms_thresh   : float
        IoU threshold for non-maximum suppression.

    Usage: 
    model = FasterRCNNWaRP(num_classes=29)
    model.train()
    loss_dict = model(images, targets)   # training
    model.eval()
    predictions = model(images)          # inference
    """

    NUM_CLASSES = 29   # 28 WaRP classes + 1 background

    def __init__(
        self,
        num_classes:  int   = NUM_CLASSES,
        pretrained:   bool  = True,
        score_thresh: float = 0.05,
        nms_thresh:   float = 0.5,
    ):
        super().__init__()

        self.num_classes = num_classes

        # Load COCO pretrained Faster R-CNN with ResNet-50 + FPN backbone.
        # box_score_thresh and box_nms_thresh control inference filtering.
        self.model = fasterrcnn_resnet50_fpn(
            weights              = "DEFAULT" if pretrained else None,
            box_score_thresh     = score_thresh,
            box_nms_thresh       = nms_thresh,
        )

        # we replace the classification head.
        # The original head outputs 91 classes (COCO)
        # We replace it with a head for num_classes
        # in_features = 1024 for ResNet-50 FPN
        in_features = self.model.roi_heads.box_predictor.cls_score.in_features
        self.model.roi_heads.box_predictor = FastRCNNPredictor(
            in_features, num_classes
        )

        if pretrained:
            print(f"[FasterRCNN] ResNet-50 FPN : COCO pretrained")
            print(f"  Classes     : {num_classes} (28 WaRP + 1 background)")
            print(f"  Parameters  : {self.count_parameters():,}")

    def forward(self, images, targets=None):
        """
        Forward pass.

        Training:   pass both images and targets -> returns loss dict
        Inference:  pass images only              -> returns predictions

        Parameters
        ----------
        images  : list of (C, H, W) tensors — variable size is fine
        targets : list of dicts with keys:
                    "boxes"  : (N, 4) float tensor  [x1, y1, x2, y2]
                    "labels" : (N,)   int64 tensor   class indices 1..28

        Returns
        -------
        Training : dict {"loss_classifier", "loss_box_reg",
                         "loss_objectness", "loss_rpn_box_reg"}
        Inference: list of dicts {"boxes", "labels", "scores"}
        """
        return self.model(images, targets)

    def freeze_backbone(self):
        """Freeze ResNet-50 + FPN. Train RPN and RoI heads only."""
        for param in self.model.backbone.parameters():
            param.requires_grad = False
        print("[FasterRCNN] Backbone frozen")

    def unfreeze_backbone(self):
        """Unfreeze everything for full fine-tuning."""
        for param in self.model.backbone.parameters():
            param.requires_grad = True
        print("[FasterRCNN] Backbone unfrozen")

    def get_param_groups(self, backbone_lr=1e-5, head_lr=1e-4):
        """
        Differential learning rates.
        Backbone already has good features → small LR.
        Heads are newly adapted to WaRP → larger LR.
        """
        backbone_params = list(self.model.backbone.parameters())
        head_params = (
            list(self.model.rpn.parameters()) +
            list(self.model.roi_heads.parameters())
        )
        return [
            {"params": backbone_params, "lr": backbone_lr},
            {"params": head_params,     "lr": head_lr},
        ]

    def count_parameters(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)