# -*- coding: utf-8 -*-
"""AML_coursework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqZ7Pkb3I5GWsqg_n6Q5OypW_tIxkLZV
"""

'''
Date: 28/03/2026
Author: Umme-Yusrah
Description: Basic working version of MobileViT
'''
#Importing libraries
import torch
import torch.nn as nn
from transformers import MobileViTForImageClassification


class MobileViT(nn.Module):

    def __init__(self, number_of_classes: int = 28,
                 freeze: bool = True):
        super(MobileViT, self).__init__()

        self.number_of_classes = number_of_classes
        self.MobileViT_model = "MobileViT-Small"  #small model that uses 5.6M parameters and have a 98% accuracy on waste classification

        #loading pre trained ViT from Hugging face
        self.pretrained_backbone = MobileViTForImageClassification.from_pretrained("apple/mobilevit-small")

        #Input features of the classifier
        input_features = self.pretrained_backbone.classifier.in_features

        #New classification head for 28 waste classes
        self.classifier = nn.Linear(input_features, number_of_classes)


        # replacing the classifcation head from the pretrained backbon of Huggingface to adapt model to the waste classification of 28 classes only
        self.pretrained_backbone.classifier = self.MobileViT_classifier

        #Two step  training strategy
        # Freeze backbone for Phase 1 training
        if freeze:
            self.freeze_backbone()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        outputs = self.pretrained_backbone(x)
        return outputs.logits


    def freeze_backbone(self):
        for parameter in self.pretrained_backbone.parameters():
            parameter.requires_grad = False

        for parameter in self.MobileViT_classifier.parameters():
            parameter.requires_grad = True

    def unfreeze_backbone(self):
        for parameter in self.pretrained_backbone.parameters():
            parameter.requires_grad = True